import { Listing } from "./types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    user_id: "user-1",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "Gastronomie",
    city: "München",
    region: "Bayern",
    country: "DE",
    title: "Etabliertes Restaurant mit Biergarten in München-Schwabing",
    description:
      "Dieses familiengeführte Restaurant mit über 25 Jahren Geschichte in Schwabing verfügt über einen charmanten Biergarten mit 80 Sitzplätzen. Vollständig eingerichtetes Lokal, eingespielte Stammkundschaft und hervorragende Lage direkt am Elisabethplatz. Verkauf aufgrund Ruhestand.",
    asking_price: 320000,
    price_confidential: false,
    annual_revenue: 780000,
    ebitda: 95000,
    employees: 12,
    founded_year: 1998,
    business_model:
      "Bayerische Küche mit Mittagstisch und Abendkarte. Hoher Stammkundenanteil, Catering für Firmenveranstaltungen.",
    competition:
      "Mehrere Restaurants in der Umgebung, jedoch einziger Biergarten im direkten Einzugsgebiet.",
    assets_included:
      "Gesamte Küchenausstattung, Mobiliar, Markenrechte, Kundenstamm",
    reason_for_sale: "Ruhestand des Eigentümers",
    company_name: "Gasthaus zum Schwabing GmbH",
    vat_number: "DE123456789",
    phone: null,
    show_phone: false,
    status_business: "active_profitable",
    plan: "plus",
    plan_expires_at: "2025-06-01",
    featured: true,
    views_count: 342,
    inquiries_count: 18,
    images: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    ],
    created_at: "2025-01-10T10:00:00Z",
    updated_at: "2025-01-10T10:00:00Z",
  },
  {
    id: "2",
    user_id: "user-2",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "IT & Tech",
    city: "Berlin",
    region: "Berlin",
    country: "DE",
    title: "Wachstumsstarkes SaaS-Unternehmen für HR-Software",
    description:
      "Spezialisiertes B2B-SaaS-Unternehmen mit einer Cloudlösung für Personalverwaltung und Lohnabrechnung. 140 aktive Unternehmenskunden, monatlich wiederkehrende Einnahmen (MRR) von €58.000. Technologisch ausgereift, skalierbar und mit starkem Team von 15 Mitarbeitern.",
    asking_price: 2100000,
    price_confidential: false,
    annual_revenue: 2150000,
    ebitda: 420000,
    employees: 15,
    founded_year: 2018,
    business_model:
      "SaaS-Modell mit jährlichen Abonnements. Durchschnittlicher Vertragswert €15.000/Jahr. Net Revenue Retention >110%.",
    competition:
      "Nische im Mittelstand, klare Differenzierung durch DSGVO-Compliance und deutschen Support.",
    assets_included:
      "Vollständiger Quellcode, Kundenstamm, Markenrechte, bestehende Verträge, Team",
    reason_for_sale: "Gründer möchte neues Projekt starten",
    company_name: "HR-Cloud Solutions GmbH",
    vat_number: "DE987654321",
    phone: "+49 30 12345678",
    show_phone: true,
    status_business: "active_profitable",
    plan: "premium",
    plan_expires_at: "2025-08-01",
    featured: true,
    views_count: 891,
    inquiries_count: 47,
    images: [
      "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80",
    ],
    created_at: "2025-01-05T09:00:00Z",
    updated_at: "2025-01-05T09:00:00Z",
  },
  {
    id: "3",
    user_id: "user-3",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "Handwerk",
    city: "Hamburg",
    region: "Hamburg",
    country: "DE",
    title: "Sanitär- und Heizungsbetrieb mit 8 Mitarbeitern",
    description:
      "Gut eingeführter Sanitär- und Heizungsbetrieb mit über 30 Jahren Geschichte in Hamburg-Eimsbüttel. Fester Kundenstamm aus Privatpersonen und Hausverwaltungen. Vollständige Fahrzeugflotte (4 Servicefahrzeuge) inklusive. Inhaber geht in Rente, Einarbeitung möglich.",
    asking_price: 480000,
    price_confidential: false,
    annual_revenue: 1200000,
    ebitda: 140000,
    employees: 8,
    founded_year: 1992,
    business_model:
      "Notfallservice, Wartungsverträge mit Hausverwaltungen, Neuinstallationen",
    competition: null,
    assets_included:
      "4 Servicefahrzeuge, Werkzeuge, Lagerbestand, Kundenstamm, Markenrechte",
    reason_for_sale: "Renteneintritt des Inhabers",
    company_name: "Klempner & Heizung Meinhardt",
    vat_number: null,
    phone: null,
    show_phone: false,
    status_business: "active_profitable",
    plan: "base",
    plan_expires_at: "2025-04-01",
    featured: false,
    views_count: 156,
    inquiries_count: 9,
    images: [
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80",
    ],
    created_at: "2025-01-15T11:00:00Z",
    updated_at: "2025-01-15T11:00:00Z",
  },
  {
    id: "4",
    user_id: "user-4",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "E-Commerce",
    city: "Wien",
    region: "Wien",
    country: "AT",
    title: "Profitabler E-Commerce Shop für nachhaltige Mode",
    description:
      "Etablierter Online-Shop für nachhaltige Damenmode mit über 12.000 Stammkunden in der DACH-Region. Starke Social-Media-Präsenz (42.000 Instagram-Follower). Proprietäres Warenwirtschaftssystem, Lieferantenverträge mit ethischen Produzenten. Betrieb vollständig remote führbar.",
    asking_price: 590000,
    price_confidential: false,
    annual_revenue: 1850000,
    ebitda: 210000,
    employees: 6,
    founded_year: 2019,
    business_model:
      "B2C E-Commerce, Direct-to-Consumer. Wöchentliche Newsletter-Kampagnen mit 38% Öffnungsrate.",
    competition: "Viele Mitbewerber, jedoch starke Markenbindung und Community.",
    assets_included:
      "Webshop (Shopify), Kundenstamm, Social-Media-Accounts, Lieferantenverträge, Lagerbestand",
    reason_for_sale: "Inhaberin erwartet zweites Kind, möchte kürzertreten",
    company_name: "GreenWear GmbH",
    vat_number: "ATU12345678",
    phone: null,
    show_phone: false,
    status_business: "active_profitable",
    plan: "plus",
    plan_expires_at: "2025-07-01",
    featured: true,
    views_count: 523,
    inquiries_count: 31,
    images: [
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80",
    ],
    created_at: "2025-01-08T14:00:00Z",
    updated_at: "2025-01-08T14:00:00Z",
  },
  {
    id: "5",
    user_id: "user-5",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "Gesundheit",
    city: "Zürich",
    region: "Zürich (CH)",
    country: "CH",
    title: "Zahnarztpraxis in bester Zürcher Lage zu verkaufen",
    description:
      "Moderne Zahnarztpraxis mit 3 vollausgestatteten Behandlungszimmern im Herzen von Zürich. Hoher Anteil Privatpatienten (65%). Eingespieltes Team aus 2 Assistentinnen und einer Hygienikerin. Alle Geräte weniger als 4 Jahre alt. Übergabe mit umfangreicher Einarbeitung möglich.",
    asking_price: null,
    price_confidential: true,
    annual_revenue: 1100000,
    ebitda: 380000,
    employees: 4,
    founded_year: 2008,
    business_model:
      "Allgemeine Zahnmedizin mit Schwerpunkt ästhetische Behandlungen und Implantologie.",
    competition: null,
    assets_included:
      "Vollständige Praxisausstattung, Patientenstamm (ca. 1.800 aktive Patienten), Mietvertrag",
    reason_for_sale: "Umzug ins Ausland",
    company_name: "Dr. med. dent. Zürich AG",
    vat_number: "CHE-123.456.789",
    phone: null,
    show_phone: false,
    status_business: "active_profitable",
    plan: "premium",
    plan_expires_at: "2025-09-01",
    featured: false,
    views_count: 287,
    inquiries_count: 14,
    images: [
      "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&q=80",
    ],
    created_at: "2025-01-12T08:00:00Z",
    updated_at: "2025-01-12T08:00:00Z",
  },
  {
    id: "6",
    user_id: "user-6",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "Gastronomie",
    city: "Frankfurt",
    region: "Hessen",
    country: "DE",
    title: "Traditionelle Bäckerei mit Café in Frankfurt-Sachsenhausen",
    description:
      "Inhabergeführte Bäckerei mit angeschlossenem Café, bekannt für hausgemachte Spezialitäten und Sachsenhäuser Ebbelwoi-Brot. 3 Filialen im Stadtgebiet, eigene Produktion. Starke regionale Bekanntheit und treuer Kundenstamm über drei Generationen.",
    asking_price: 850000,
    price_confidential: false,
    annual_revenue: 2300000,
    ebitda: 185000,
    employees: 22,
    founded_year: 1978,
    business_model: "Handwerkliche Bäckerei + Café-Betrieb + Großhandel",
    competition: "Einzige traditionelle Handwerksbäckerei der Gegend.",
    assets_included:
      "Bäckerei-Ausrüstung, 3 Ladeneinheiten (Mietverträge), Rezepturen, Fahrzeuge, Marke",
    reason_for_sale: "Keine Nachfolge in der Familie",
    company_name: "Bäckerei Müller KG",
    vat_number: "DE234567890",
    phone: "+49 69 98765432",
    show_phone: true,
    status_business: "active_profitable",
    plan: "plus",
    plan_expires_at: "2025-06-15",
    featured: false,
    views_count: 198,
    inquiries_count: 11,
    images: [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
    ],
    created_at: "2025-01-20T07:00:00Z",
    updated_at: "2025-01-20T07:00:00Z",
  },
  {
    id: "7",
    user_id: "user-7",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "Dienstleistungen",
    city: "Düsseldorf",
    region: "Nordrhein-Westfalen",
    country: "DE",
    title: "Steuerberatungskanzlei mit 380 Mandanten",
    description:
      "Etablierte Steuerberatungskanzlei in zentraler Lage Düsseldorfs. Breites Mandantenportfolio aus KMU und Freiberuflern. Zwei angestellte Steuerberater, keine Abhängigkeit vom Inhaber. Digitalisierter Betrieb (DATEV), bereit für digitale Übergabe.",
    asking_price: 720000,
    price_confidential: false,
    annual_revenue: 890000,
    ebitda: 280000,
    employees: 7,
    founded_year: 2003,
    business_model:
      "Laufende Mandatsbetreuung (Buchhaltung, Jahresabschlüsse, Steuererklärungen) + Beratungsmandate.",
    competition: null,
    assets_included: "Mandantenstamm, Software (DATEV), Büroausstattung, Marke",
    reason_for_sale: "Ruhestand",
    company_name: "Schneider Steuerberatung GmbH",
    vat_number: "DE345678901",
    phone: null,
    show_phone: false,
    status_business: "active_profitable",
    plan: "premium",
    plan_expires_at: "2025-10-01",
    featured: true,
    views_count: 412,
    inquiries_count: 22,
    images: [
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    ],
    created_at: "2025-01-03T09:00:00Z",
    updated_at: "2025-01-03T09:00:00Z",
  },
  {
    id: "8",
    user_id: "user-8",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "Gesundheit",
    city: "Graz",
    region: "Steiermark",
    country: "AT",
    title: "Fitnessstudio mit 1.200 aktiven Mitgliedern in Graz",
    description:
      "Modernes Fitnessstudio mit 850 qm Trainingsfläche, hochwertigem Equipment und Kursraum. 1.200 aktive Mitglieder mit durchschnittlicher Mitgliedsdauer von 3,5 Jahren. Solide Mitarbeiterstruktur (6 Trainer, 2 Empfang). Langfristiger Mietvertrag (noch 8 Jahre).",
    asking_price: 440000,
    price_confidential: false,
    annual_revenue: 960000,
    ebitda: 128000,
    employees: 8,
    founded_year: 2014,
    business_model: "Monatliche Mitgliedschaften, 10er-Blöcke, Personal Training.",
    competition: "Gut positioniert im Premium-Segment, 2 Wettbewerber in 3 km.",
    assets_included:
      "Gesamte Fitnessausstattung, Mitgliederstamm, Software, Mietvertrag",
    reason_for_sale: "Inhaber verlegt Wohnsitz nach Wien",
    company_name: "FitLife Graz GmbH",
    vat_number: "ATU87654321",
    phone: null,
    show_phone: false,
    status_business: "active_profitable",
    plan: "base",
    plan_expires_at: "2025-05-01",
    featured: false,
    views_count: 167,
    inquiries_count: 7,
    images: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    ],
    created_at: "2025-01-18T12:00:00Z",
    updated_at: "2025-01-18T12:00:00Z",
  },
  {
    id: "9",
    user_id: "user-9",
    status: "active",
    type_of_operation: "anteilsuebertragung",
    category: "Produktion",
    city: "Leipzig",
    region: "Sachsen",
    country: "DE",
    title: "Produktionsbetrieb für industrielle Verpackungslösungen",
    description:
      "Mittelständischer Hersteller von Spezialverpackungen für die Pharma- und Lebensmittelindustrie. Zertifiziert nach ISO 9001 und ISO 15378. Moderne Produktionsanlage (2.400 qm), langfristige Lieferverträge mit 3 Großkunden (DAX-Konzerne). Anteilsverkauf von 60% möglich.",
    asking_price: 3500000,
    price_confidential: false,
    annual_revenue: 4200000,
    ebitda: 630000,
    employees: 38,
    founded_year: 2005,
    business_model:
      "B2B-Produktion auf Bestellung + Standardsortiment. 70% Umsatz aus Langzeitverträgen.",
    competition: "Spezialnische mit hohen Einstiegshürden durch Zertifizierungen.",
    assets_included: "60% Unternehmensanteile, alle Anlagen bleiben im Betrieb",
    reason_for_sale: "Strategischer Investor gesucht für Wachstumsfinanzierung",
    company_name: "PackTech Leipzig GmbH",
    vat_number: "DE456789012",
    phone: "+49 341 11223344",
    show_phone: false,
    status_business: "active_profitable",
    plan: "premium",
    plan_expires_at: "2025-11-01",
    featured: false,
    views_count: 234,
    inquiries_count: 16,
    images: [
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    ],
    created_at: "2025-01-22T10:00:00Z",
    updated_at: "2025-01-22T10:00:00Z",
  },
  {
    id: "10",
    user_id: "user-10",
    status: "active",
    type_of_operation: "vollstaendige_uebertragung",
    category: "Immobilien",
    city: "Köln",
    region: "Nordrhein-Westfalen",
    country: "DE",
    title: "Immobilienmaklerunternehmen mit starker Kölner Marktposition",
    description:
      "Wachstumsstarkes Immobilienmaklerunternehmen mit Fokus auf Wohnimmobilien in Köln und Umgebung. 6 erfahrene Makler, eigenes CRM-System, professionelles Online-Marketing. 2024 wurden 87 Einheiten vermittelt. Starke Arbeitgebermarke und Bewerbungseingang.",
    asking_price: 1200000,
    price_confidential: false,
    annual_revenue: 2800000,
    ebitda: 340000,
    employees: 9,
    founded_year: 2012,
    business_model:
      "Wohnimmobilienvermittlung Kauf & Miete + Vermietungsmanagement.",
    competition: "Etablierter dritter Platz im Kölner Markt.",
    assets_included: "Kundenstamm, CRM-Software, Markenrechte, Mietvertrag Büro",
    reason_for_sale: "Gründerin möchte ins Ausland",
    company_name: "Kölner Immobilien GmbH",
    vat_number: "DE567890123",
    phone: null,
    show_phone: false,
    status_business: "active_profitable",
    plan: "plus",
    plan_expires_at: "2025-07-15",
    featured: true,
    views_count: 389,
    inquiries_count: 24,
    images: [
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    ],
    created_at: "2025-01-06T13:00:00Z",
    updated_at: "2025-01-06T13:00:00Z",
  },
];

export const CATEGORY_ICONS: Record<string, string> = {
  Gastronomie: "🍽️",
  Einzelhandel: "🛍️",
  Produktion: "🏭",
  Dienstleistungen: "💼",
  "IT & Tech": "💻",
  Gesundheit: "🏥",
  Handwerk: "🔧",
  Immobilien: "🏢",
  "E-Commerce": "🛒",
  Bildung: "📚",
  "Transport & Logistik": "🚛",
  "Finanzen & Versicherung": "📊",
  "Medien & Marketing": "📱",
  Landwirtschaft: "🌾",
  Energie: "⚡",
};
